#### Functions for feature engineering ####

library(dplyr)

#### Schema capture ####
## Captures the schema of the training dataset (e.g. features, factor levels)
capture_schema <- function(model.data) {
  
  ## model.data: data frame of training data
  
  # Generate dataframe capturing feature names and classes. Leave levels empty to be 
  # allocated in a future step.
  model.schema <- data.frame(feature = colnames(model.data),
                             type = sapply(model.data, class))
  
  # List out levels
  levels.list <- list()
  for (i in 1:nrow(model.schema)) {
    levels.list[[as.character(model.schema$feature[i])]] <- ifelse(model.schema$type[i] == "factor",
                                                                   list(levels(model.data[, as.character(model.schema$feature[i])])),
                                                                   0)
  }
  
  # List out levels
  class.list <- list()
  for (i in 1:nrow(model.schema)) {
    class.list[[as.character(model.schema$feature[i])]] <- as.character(model.schema$type[i])
  }
  
  # Combine lists
  schema.list <- list(classes = class.list, levels = levels.list)
  
  # Return result
  return(schema.list)

}



#### Verify schema of new dataset ####
## Checks that factor levels of new dataset match the training set

check_schema <- function(new.data, model.schema) {
  
  ## new.data: new data frame being checked
  ## model.schema: schema list generated by capture_schema
  
  model.check <- data.frame(feature = names(model.schema$classes),
                            class = as.character(model.schema$classes))
  
  model.check$in.new.data <- ifelse(model.check$feature %in% colnames(new.data), "MATCH", "MISSING")
  
  model.check$level.check <- NA
  
  for (i in 1:nrow(model.check)) {
    target.feature <- as.character(model.check$feature[i])
    
    if(model.check$class[i] == "factor") {
      # Get schema and new data levels
      schema.levels <- unlist(model.schema$levels[[target.feature]])
      new.data.levels <- levels(new.data[, target.feature])
      
      # Write match results to table
      model.check$level.check[i] <- ifelse(identical(schema.levels, new.data.levels), "MATCH", "NEW LEVELS")
    }
  }
  
  return(model.check)
  
}

